---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: osxc.packages
    brew_taps:
    - Homebrew/python
    - ClockworkNet/cmc
    brew_packages:
    - android-sdk
    - casperjs
    - cmc
    - ctags
    - curl
    - git
    - go
    - hub
    - matplotlib
    - mercurial
    - mplayer
    - nmap
    - python
    - rdesktop
    - reattach-to-user-namespace
    - the_silver_searcher
    - tintin
    - tmux
    - zsh
    cask_packages:
    - arduino
    - audacity
    - bittorrent-sync
    - citrix-receiver
    - dropbox
    - firefox
    - fuze
    - gimp
    - google-chrome
    - google-drive
    - hipchat
    - iterm2
    - keepassx
    - keka
    - libreoffice
    - synergy
    - tunnelblick
    - vagrant
    - xquartz
    - parallels-desktop
