---
- name: Setup dotfiles
  git: "repo={{ dotfiles_repo }} dest={{ dotfiles_dest }} version={{ dotfiles_version }} accept_hostkey=yes"

- name: Install zprezto
  file: src={{ item.path }} dest={{item.dest}} state=link
  with_items:
    - { path: '~/lib/dotfiles/zsh/prezto', dest: '~/.zprezto' }
    - { path: '~/.zprezto/runcoms/zlogin', dest: '~/.zlogin' }
    - { path: '~/.zprezto/runcoms/zlogout', dest: '~/.zlogout' }
    - { path: '~/.zprezto/runcoms/zpreztorc', dest: '~/.zpreztorc' }
    - { path: '~/.zprezto/runcoms/zprofile', dest: '~/.zprofile' }
    - { path: '~/.zprezto/runcoms/zshenv', dest: '~/.zshenv' }
    - { path: '~/.zprezto/runcoms/zshrc', dest: '~/.zshrc' }

- name: Install vim
  file: src={{ item.path }} dest={{item.dest}} state=link
  with_items:
    - { path: '~/lib/dotfiles/vim', dest: '~/.vim' }
    - { path: '~/lib/dotfiles/vim/vimrc', dest: '~/.vimrc' }

- name: Install neobundle vim plugin
  git: "repo=https://github.com/Shougo/neobundle.vim dest=~/.vim/bundle/neobundle.vim accept_hostkey=yes"

- name: Git dotfiles
  file: src={{ item.path }} dest={{item.dest}} state=link
  with_items:
    - { path: '~/lib/dotfiles/git/gitconfig', dest: '~/.gitconfig' }
    - { path: '~/lib/dotfiles/git/gitignore', dest: '~/.gitignore' }
